# Generated by Django 5.0.1 on 2025-05-26 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analyzed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='details',
        ),
        migrations.AddField(
            model_name='analysis',
            name='acousticness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='comparison_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='danceability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='instrumentalness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='liveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_bandwidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_centroid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_rolloff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='speechiness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='time_signature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='valence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='analysis_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.track'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='api.mood'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
