# Generated by Django 5.0.1 on 2025-05-31 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_analyzed_at_analysis_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='comparison_result',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='instrumentalness',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='key',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='spectral_bandwidth',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='spectral_centroid',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='spectral_rolloff',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='time_signature',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='valence',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('title', 'artist')},
        ),
        migrations.AddField(
            model_name='analysis',
            name='channels_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='clipping_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysis',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='fingerprint_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='frame_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='frame_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='max_amplitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rms_amplitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='silence_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='color_code',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='mood',
            name='valence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='channels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='dejavu_song_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='fingerprint_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='fingerprint_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error'), ('not_found', 'No encontrado en base de datos')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='fingerprints_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='is_reference_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='reference_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='sample_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_purpose',
            field=models.CharField(choices=[('recognition', 'Para reconocimiento'), ('reference', 'Track de referencia'), ('other', 'Otro')], default='recognition', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name', 'user')},
        ),
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='music_files/')),
                ('duration', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('key', models.CharField(max_length=10, null=True)),
                ('loudness', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('offset_seconds', models.FloatField(default=0.0)),
                ('fingerprinted_confidence', models.IntegerField(default=0)),
                ('recognition_status', models.CharField(choices=[('processing', 'Procesando'), ('found', 'Encontrado'), ('not_found', 'No encontrado'), ('error', 'Error')], default='processing', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('recognition_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dejavu_result', models.JSONField(blank=True, null=True)),
                ('recognized_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='api.track')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='api.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='track',
            name='analysis_error',
        ),
        migrations.RemoveField(
            model_name='track',
            name='analysis_status',
        ),
    ]
