# Generated by Django 5.0.1 on 2025-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_analysis_acousticness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='ID de Spotify para vincular con AudD', max_length=50, null=True, unique=True),
        ),
    ]
