# Generated by Django 5.0.1 on 2025-06-01 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_track_spotify_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=100, null=True)),
                ('apple_music_url', models.URLField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_analyses', to='api.track')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_analyses', to='api.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Música',
                'verbose_name_plural': 'Análisis de Música',
                'ordering': ['-created_at'],
            },
        ),
    ]
